dwavesystems/dwave-system

dwave/system/package_info/package_info.py
dwave/system/samplers/dwave_sampler.py
tests/test_dwave_sampler.py
tests_integration/test_dwave_sampler_with_system.py

Bugfix #36

---

README.rst
docs/reference/composites/embedding.rst
docs/reference/composites/index.rst
docs/reference/composites/tiling.rst
docs/reference/composites/virtual_graph.rst
docs/reference/samplers/dwave_sampler.rst
docs/reference/samplers/index.rst

@arcondello: Updated overview description in README and added overview content for RtD on samplers & composites

Add overview content 

---

docs/reference/samplers/dwave_sampler.rst

Fix rebase mess

---

dwave/system/composites/tiling.py
tests/test_tiling_composite.py

Fix bug where TilingComposite was returning too many variables

---

docs/reference/composites/tiling.rst
dwave/system/composites/embedding.py
dwave/system/composites/tiling.py

@arcondello also made a minor update to embedding

Update composites tiling

---

dwave/system/composites/embedding.py
dwave/system/composites/tiling.py
dwave/system/composites/virtual_graph.py
dwave/system/embedding/embedding.py
requirements.txt
setup.py

* Remove dependency on dwave-embedding-utilities and use dimod's built-in embedding

Use dimod>=0.6.7

---

dwave/system/composites/virtual_graph.py

@arcondello copy & paste error from my Python CMD

Fix ising --> qubo method

---

README.rst

The .. note:: directive doesn't show up on the README.md but does in the sphinx build.

highlight change in install step

---

README.rst
docs/ocean.rst

Closes Issue #81 and broken link to Ocean Overview

---

README.rst

Clarify install instructions for dwave-drivers in readme

---

dwave/system/composites/embedding.py
requirements.txt
setup.py

Add chain break statistics to embedding composites

---

dwave/embedding/chimera.py
tests/unit/test_embedding_chimera.py

Fix error message in chimera.find_grid_embedding

---

dwave/system/composites/embedding.py
dwave/system/composites/tiling.py
dwave/system/composites/virtual_graph.py
dwave/system/samplers/dwave_sampler.py

Nothing needed, so just fixed some broken links and a minor change to solver definition.

Update for feature-based solver selection

---

requirements.txt
setup.py

Fix needed for https://github.com/dwavesystems/dwave-ocean-sdk/pull/24

Remove dwave-networkx version upper bound

---

dwave/embedding/chain_breaks.py
tests/test_embedding_chain_breaks.py

Fix minimizeEnegy function, add test

---

docs/reference/embedding.rst
dwave/system/composites/embedding.py
dwave/system/composites/virtual_graph.py

Closes #157 and fixes some stuff you broke

Fix Issue #157 VirtualGraphComposite()

---

dwave/embedding/pegasus.py
requirements.txt
setup.py
tests/test_embedding_pegasus.py

This depends on https://github.com/dwavesystems/dwave_networkx/pull/95

added clique-embedding support for nice pegasus coordinates

---

dwave/embedding/utils.py
tests/test_embedding_utils.py

chain_break_frequency respects num_occurrences

---

dwave/system/composites/tiling.py
dwave/system/package_info.py

I need this for the new JN. Thanks!

Add timing info to TilingComposite

---

dwave/system/composites/embedding.py
dwave/system/testing.py
tests/test_embedding_composite.py

Add chain break resolution method to embedding composites

---

dwave/embedding/pegasus.py
requirements.txt
setup.py

sorry... this is gonna make some versioning hell

updated to reflect change in pegasus nice_coordinates

---

dwave/system/composites/embedding.py
tests/test_embedding_composite.py

Closes https://github.com/dwavesystems/dimod/issues/487

Use dfs in EmbeddingComposite to find child structure

---

dwave/system/composites/embedding.py
tests/test_embedding_composite.py

Make EmbeddingComposite scale aware

---

dwave/system/composites/embedding.py
dwave/system/samplers/dwave_sampler.py
tests/qpu/test_dwave_sampler_with_system.py
tests/test_dwave_sampler.py
tests/test_embedding_composite.py

Does not make use of the parameter added in https://github.com/dwavesystems/dwave-cloud-client/pull/319 but in the future it could.

AutoEmbeddingComposite handles unstructured children

---

dwave/system/samplers/dwave_sampler.py
tests/qpu/test_dwave_sampler_with_system.py
tests/test_dwave_sampler.py

Closes #196 
#194 made the necessary changes in `DWaveSampler.sample_ising` but not in `.sample_qubo`. We should probably just overwrite `.sample` instead.

Raise BinaryQaudraticModelStructureError for mismatched QUBO

---

dwave/system/samplers/dwave_sampler.py
tests/qpu/test_dwavesampler.py

DWaveSampler.sample_ising accepts a list with 0 biases

---

dwave/embedding/chain_breaks.py
dwave/embedding/transforms.py
tests/test_embedding_chain_breaks.py
tests/test_embedding_composite.py

Adds a test for the failing example in #206 so it stays on our radar, still need to decide on a solution.
Closes #206

Fix MinimizeEnergy chain break method

---

dwave/system/composites/cutoffcomposite.py
tests/test_polycutoffcomposite.py

Fix isolated variables in PolyCutOffComposite

---

docs/conf.py
docs/intro.rst
docs/reference/composites.rst
docs/reference/embedding.rst
docs/reference/samplers.rst
dwave/embedding/pegasus.py
dwave/system/composites/cutoffcomposite.py
dwave/system/composites/embedding.py
dwave/system/samplers/dwave_sampler.py

Some wording for cutoff classes left open for next chunk

Refresh docstrings & examples (part 1)

---

docs/reference/embedding.rst
dwave/embedding/chain_breaks.py
dwave/embedding/chimera.py
dwave/embedding/diagnostic.py
dwave/embedding/pegasus.py
dwave/embedding/transforms.py
dwave/embedding/utils.py
dwave/system/composites/embedding.py
dwave/system/composites/tiling.py
dwave/system/composites/virtual_graph.py

@arcondello, either review this longer one or merge part 2, I'll rebase, and you can then review the diff.
Closes #214

Refresh docstrings & examples (part 3)

---

dwave/embedding/chimera.py
tests/test_embedding_chimera.py

Fix for two variable clique (k2) embedding

---

requirements.txt
setup.py

See https://github.com/dwavesystems/dwave_networkx/pull/134

Support networkx>=2.4

---

dwave/embedding/chimera.py
dwave/embedding/pegasus.py
requirements.txt
setup.py
tests/test_embedding_pegasus.py

WIP; have not added tests or bumped requirements for newest dwave_networkx
addresses issue #238

fix issue238, broken chains in find_clique_embedding when target graph has missing edges

---

dwave/system/composites/embedding.py
dwave/system/samplers/dwave_sampler.py
dwave/system/warnings.py
requirements.txt
setup.py
tests/test_dwavesampler.py
tests/test_embedding_composite.py

The default warning action can now also be overwritten on the `WarningHandler`.

EnergyScaleWarning and ChainStrengthWarning

---

docs/index.rst

I'm thinking of adding these to all Ocean tools. Not to be merged yet.

Add version notice (post-SDK update)

---

dwave/system/samplers/dwave_sampler.py
dwave/system/warnings.py
tests/test_dwavesampler.py

add `TooFewSamplesWarning`
#249

Too few samples warning

---

docs/reference/composites.rst
docs/reference/embedding.rst

Minor, but the build warnings were annoying

Fix links to SDK

---

dwave/embedding/diagnostic.py
tests/test_embedding_diagnostic.py

changed embedding diagnostic to play nicer with overlapped embeddings

---

dwave/embedding/transforms.py
tests/test_embedding_transforms.py

Requires the changes from https://github.com/dwavesystems/dimod/pull/616

Support dimod 0.9.x

---

dwave/system/warnings.py

As suggested by Joel P. for the inspector

Updated warning description for broken chain in lowest energy sample

---

docs/intro.rst
docs/reference/embedding.rst
docs/reference/samplers.rst

Removes duplicate content post https://github.com/dwavesystems/dwave-ocean-sdk/pull/62
Assumes we agree on proposed structure; alternative is for content to live here and be pulled into SDK top level.
NOT TO BE MERGED BEFORE 62.

(Awaiting SDK update) Integrate SDK concepts locally

---

dwave/system/samplers/dwave_sampler.py
requirements.txt
setup.py
tests/test_dwavesampler.py

Use the dwave-cloud-client's Solver.sample_bqm method

---

dwave/embedding/transforms.py
tests/test_embedding_transforms.py

Raise correct exception when embedding with zero chain length

---

dwave/system/composites/embedding.py
dwave/system/warnings.py
tests/test_embedding_composite.py

Don't raise a chain strength warning when chains have length <= 1

---

dwave/system/samplers/leap_hybrid_sampler.py
tests/test_leaphybridsolver.py

Hybrid sampler uses the correct client

---

setup.py

And I'll need a tag, sir, for a requirement of https://github.com/dwavesystems/dwave-inspector/pull/86

Add tabu to setup

---

dwave/system/samplers/leap_hybrid_sampler.py
dwave/system/testing.py
tests/test_leaphybridsolver.py

There might be a syntax for this.

Specify problem type in LeapHybridSampler

---

dwave/system/testing.py

Fix topology.shape in MockDWaveSampler to match C4

---

dwave/embedding/transforms.py
tests/test_embedding_composite.py

Add dimod BQM tests for EmbeddingComposites

---

dwave/system/composites/embedding.py
tests/qpu/test_embeddingcomposite.py
tests/test_embedding_composite.py

Make EmbeddingComposite and subclasses non-blocking

---

docs/reference/samplers.rst
dwave/system/samplers/dwave_sampler.py
tests/test_dwavesampler.py

Resolves second part of https://github.com/dwavesystems/dimod/issues/647.

Added to_networkx_graph() to DWaveSampler

---

dwave/system/samplers/clique.py

Closes #318 
Implemented suggestion from Jack's comment in [#313](https://github.com/dwavesystems/dwave-system/pull/313#discussion_r457136387).

Implemented chain strength improvement in DWaveCliqueSampler

---

dwave/embedding/__init__.py
dwave/embedding/transforms.py
dwave/embedding/utils.py
dwave/system/composites/embedding.py
tests/test_embedding_composite.py
tests/test_embedding_transforms.py
tests/test_embedding_utils.py
tests/test_virtual_graph_composite.py

I was making some changes that might take some time to get approval.  Along the way I found some low-bar performance improvements (on the order of 10x for a K64 embedding, significantly more in the case of `FixedEmbeddingComposite` and the like) which are less controversial.

embed_bqm refactor

---

dwave/system/samplers/clique.py

DWaveCliqueSampler chain strength

---

dwave/system/samplers/clique.py
tests/test_dwavecliquesampler.py

It is useful to get the clique embedding of a specific size, not just the maximum.

Add DWaveCliqueSampler.clique

---

docs/reference/embedding.rst
dwave/embedding/chain_strength.py
dwave/embedding/chain_strengths.py
dwave/embedding/transforms.py
requirements.txt
setup.py
tests/test_embedding_chain_strength.py
tests/test_embedding_chain_strengths.py

- Add chain strength function for scaling to problem bias range
- Add examples to the documentation

Add new chain strength function 

---

README.rst
docs/conf.py
docs/index.rst
docs/intro.rst
docs/reference/embedding.rst
docs/reference/index.rst
docs/reference/samplers.rst
docs/reference/warnings.rst
dwave/embedding/chain_breaks.py
dwave/embedding/chimera.py
dwave/embedding/transforms.py
dwave/system/composites/cutoffcomposite.py
dwave/system/composites/embedding.py
dwave/system/composites/reversecomposite.py
dwave/system/composites/tiling.py
dwave/system/composites/virtual_graph.py
dwave/system/samplers/clique.py
dwave/system/samplers/dwave_sampler.py
dwave/system/samplers/leap_hybrid_sampler.py

Also fixes quite a number of dead refs, adds some new examples, etc.

Add support for Pegasus

---

dwave/embedding/transforms.py
tests/test_embedding_transforms.py

Fix backwards compatibility break with embed_bqm

---

dwave/embedding/transforms.py
tests/requirements.txt
tests/test_embedding_transforms.py

https://github.com/dwavesystems/dimod/pull/690 may provide a better long term solution
Fixes doctest failure in https://github.com/dwavesystems/dwave-ocean-sdk/pull/95

Fix embed_bqm returning a BQM that can't have its vartype changed

---

dwave/system/samplers/leap_hybrid_sampler.py

Addresses https://github.com/dwavesystems/dwave-system/pull/349/files#r494209296
More tests needed, see #351

Correctly propagate kwargs through LeapHybridDQMSampler.sample

---

README.rst
docs/intro.rst
docs/reference/samplers.rst
dwave/system/samplers/clique.py
dwave/system/samplers/dwave_sampler.py
dwave/system/samplers/leap_hybrid_sampler.py

This is to close https://github.com/dwavesystems/dwave-system/issues/350

Update for DQM 

---

dwave/system/samplers/leap_hybrid_sampler.py
requirements.txt

@randomir for Friday's request

Replace LeapHybridDQMSolver's ``compressed`` parameter with ``compress``

---

requirements.txt
setup.py

See https://github.com/dwavesystems/dimod/issues/730, https://github.com/dwavesystems/dwave-cloud-client/pull/435

Require dimod>=0.9.10

---

dwave/embedding/transforms.py
tests/test_embedding_transforms.py

Closes https://github.com/dwavesystems/dimod/issues/737

Make EmbeddedStructure deepcopy-able and fix EmbeddedStructure.copy

---

dwave/system/warnings.py
tests/test_embedding_composite.py

Update warnings to account for dictionary chain strengths

---

dwave/system/composites/reversecomposite.py
requirements.txt
setup.py
tests/test_reverse_composite.py

Update ReverseBatchStatesComposite to use dimod's Initialized ABC

---

.appveyor.yml
.circleci/config.yml
requirements.txt

Refactor circle-ci

---

dwave/system/samplers/leap_hybrid_sampler.py
tests/test_leaphybridsolver.py

Fix hybrid solvers selection (version sort)

---

dwave/embedding/transforms.py
dwave/system/composites/embedding.py
dwave/system/samplers/clique.py

Fix chain_strength in DWaveCliqueSampler docstring

---

dwave/system/testing.py

One fix (to ``j_range`` lower boundary) and others just nice to have (for example, useful for doctests on system documents)

Add some mock properties

---

.circleci/config.yml
dwave/embedding/transforms.py
dwave/system/composites/cutoffcomposite.py
dwave/system/samplers/leap_hybrid_sampler.py
requirements.txt
setup.py
tests/test_embedding_transforms.py

Closes #394 as redundant, but leaving that as a PR for folks who have been merging from it.

Support/Test dimod `dimod>=0.9.11,<=0.10.0.dev7`

---

dwave/system/samplers/leap_hybrid_sampler.py
tests/qpu/test_leaphybriddqmsampler.py

Closes https://github.com/dwavesystems/dwave-system/issues/410

Properly account for DQMs with offsets in LeapHybridDQMSampler

---

setup.py

See https://github.com/dwavesystems/dimod/pull/981.

Resolve dependency conflicts with dimod 0.9 and 0.10

---

dwave/system/samplers/dwave_sampler.py
requirements.txt
setup.py

By de-duping problem check, we're speeding-up the sampling call.

Speed-up sampling a little bit

---

dwave/system/samplers/leap_hybrid_sampler.py

I'll let this run in CI while I test locally

Skip tests on LeapHybridCQMSampler until we mock it

---

docs/reference/composites.rst
dwave/system/composites/tiling.py

@jackraymond, the num_tiles & embeddings properties seem useful for users too (I use them). Also fixed a few formatting problems

Add TilingComposite properties num_tiles & embeddings and some formatting to docs

---

.appveyor.yml
.circleci/config.yml
setup.py

Support dimod~=0.11.0
Drop support for Python 3.6

Update dependency versions

---

docs/reference/warnings.rst

Fixes the CI failure for https://github.com/dwavesystems/dwave-ocean-sdk/pull/201

Remove doc that depends on inspector import

---

dwave/system/samplers/dwave_sampler.py
tests/test_dwavesampler.py

Fixes #477, with a caveat -- user-supplied (or default num qubits-based) solver preference is ignored on `trigger_failover()`. We override `order_by` in order to de-prioritize failed solvers.
In summary, this is a quickfix for #477, and a nicer fix should respect the lower-level solver preference, but penalize failed solvers. This seems hard to implement in dwave-system without a lot of code duplication from dwave-cloud-client. One possible, and pretty general, approach is to apply `order_by` transformations sequentially (in the cloud-client), one per config level, instead of higher-level setting overridding a lower-level setting.

Enhance QPU failover by penalizing failed solvers

---

requirements.txt
tests/test_dwavesampler.py

Closes https://github.com/dwavesystems/dwave-system/issues/494

Add networkx==2.4 to requirements.txt

---

dwave/system/composites/reversecomposite.py

Closes https://github.com/dwavesystems/dwave-system/issues/516

Remove conditional aggregation from ``ReverseBatchStatesComposite``

---

tests/test_reverse_composite.py

Unit test broken in https://github.com/dwavesystems/dwave-system/pull/517

Fix failed unittest 

---

.circleci/config.yml

This fixes a bug introduced in 3eb61fe.

Fix CI deploy job (version check)

---

dwave/system/composites/cutoffcomposite.py
dwave/system/composites/embedding.py
dwave/system/composites/linear_ancilla.py
dwave/system/composites/reversecomposite.py
dwave/system/composites/tiling.py
dwave/system/samplers/clique.py
dwave/system/samplers/dwave_sampler.py
dwave/system/samplers/leap_hybrid_sampler.py
dwave/system/testing.py
requirements.txt
setup.py
tests/test_composites_common.py

Close #555.
Note: tests require dimod 0.12.20 which is yet to be released.

Make samplers and composites scoped

---

dwave/system/package_info.py

1.30.0
---
-   Make samplers and composites scoped. See [\#555](https://github.com/dwavesystems/dwave-system/issues/555).
-   Restructure and update references for unified documentation. See [\#560](https://github.com/dwavesystems/dwave-system/pull/560).
-   Add multiparameter pseudolikelihood estimation, include background susceptibility. See [\#562](https://github.com/dwavesystems/dwave-system/pull/562).

Release 1.30.0

---

.circleci/config.yml
README.rst

Also, while fixing CI, modernize the build/deploy steps a bit (ref [dwave-experimental](https://github.com/dwavesystems/dwave-experimental/blob/main/.circleci/config.yml)).
Still needs a CI overhaul, but that's for a separate PR.

Update CI to make sure readme is valid on each build
