dwave/system/composites/embedding.py, tests/test_embedding_composite.py
`dimod.embed_bqm()` should be reverted to not handle this edge case, since it is now handled here and `dimod.unembed_response()` does not handle it.
=> Handle singletons in EmbeddingComposite

dwave/system/composites/virtual_graph.py, dwave/system/flux_bias_offsets/flux_bias_offsets.py
This fixes two bugs in VirtualGraph:
* `chain_strength` was not being passed properly to `get_flux_biases`.  This means that the flux biases always assumed the default chain strength of 1, which will give incorrect flux biases for other chain strengths.
* If `dwave-system-tuning` is not installed, the import failed silently.  Now there is a warning.  Additionally, failure gives `flux_biases = []`, which later caused an error.  This is now fixed.
=> Fixing bugs in VirtualGraph 

requirements.txt, setup.py
Patch version number increase doesn't indicate this, but `0.4.2` adds some significant improvements!
=> Use latest and greatest `dwave-cloud-client`

CONTRIBUTING.rst, LICENSE, docs/conf.py, docs/glossary.rst, docs/ocean.rst, docs/reference/composites/index.rst, docs/reference/composites/tiling.rst, docs/reference/intro.rst, dwave/system/composites/embedding.py, dwave/system/composites/tiling.py, dwave/system/composites/virtual_graph.py, dwave/system/samplers/dwave_sampler.py
@arcondello,  this moves to .com version of RtDs, also adds draw_tiling function to RtD, and fixes some standing build errors ("...dwave_sampler.py:docstring of dwave.system.samplers.DWaveSampler.validate_anneal_schedule:19: WARNING: Unexpected indentation.")
=> Use intersphinx instead of explicit links

dwave/system/composites/embedding.py, tests/unit/test_embedding_composite.py
- Code and unit tests for LazyEmbeddingComposite
- LazyEmbeddingComposite inherits from FixedEmbeddingComposite
- The difference between LazyEC and FixedEC is that the embedding in LazyEC is automatically found by minorminer rather than provided by the user.
=> Adtt 392/lazy embedding composite v2

dwave/embedding/chimera.py, tests/test_dwave_sampler.py, tests/test_embedding_composite.py
Added special logic to create optimal clique embeddings for cliques of size 1 and 2, which can be done with single-qubit chains.  Previously the dwave.system.chimera.find_clique_embedding method would return embeddings with chains of length 2 for these small cliques, which is suboptimal.
Closes #166
=> Fixes issue #166 by adding special logic for small clique embeddings.

dwave/system/composites/virtual_graph.py, tests/qpu/test_virtual_graph_composite.py
Fixes a chain strength bug and simplifies the code. But the main virtual graph logic still could use some refactoring, and this does not address #104 (though it gets part-way there by subclassing `FixedEmbeddingComposite`).
=> Partial refactor of Virtual Graph

dwave/embedding/chimera.py
Currently gives something like this for an iterable, for example BQM.variables:
```
ValueError: cannot find a K(KeysView(<dimod.views.bqm.LinearView object at 0x7f9bee7b0348>), ()) embedding for given Chimera lattice 
```
which would have been clearer as, for example, "cannot find a K8 embedding for given Chimera lattice"
Might also consider showing both: "cannot find a K8 embedding for KeysView(<dimod.views.bqm.LinearView object at 0x7f9bee7b0348>), () for given Chimera lattice"
```
raise ValueError("cannot find a K{} embedding for {} for given Chimera lattice".format(len(nodes), k))
```
=> Improve error message

dwave/system/samplers/dwave_sampler.py, tests/qpu/test_dwavesampler.py, tests/test_dwavesampler.py
The main change is altering the behaviour introduced in #201 (which fixed bug #200) to match the cloud-client's behaviour which does not ignore all the 0 biases, but rather ignores 0 biases on missing qubits.
This makes the sampler inconsistent with `BQM.from_ising` which _does not_ ignore any variables. However
```
sampler.sample_ising([0, 0, 0], {})
```
is a valid use case (wanting to sample randomly from 3 qubits) and should be supported.
Note that we don't (yet) support
```
sampler.sample_ising([0, float('nan'), 0], {})
```
nor
```
sampler.sample_ising(np.asarray([0, np.nan, 0])
```
or numpy arrays at all.
=> DWaveSampler fixes

dwave/system/composites/embedding.py
Should fix the failing tests in https://circleci.com/gh/dwavesystems/dwave-hybrid/2779
https://github.com/dwavesystems/dimod/pull/500 changed `child_structure_dfs` to raise a `ValueError`, this PR updates `AutoEmbeddingComposite` to match.
=> Catch the correct exception for child_structure_dfs in dimod

dwave/embedding/transforms.py, dwave/system/composites/embedding.py, tests/test_embedding_composite.py
Closes #76 
*Additional Context*
I am of two minds about defaulting to True, on the one hand it is pretty harmless to always include it, on the other hand the embedding composite is conceptually supposed to abstract it away totally so it feels like an abstraction break.
=> Add embedding to sample sets returned by embedding composites

dwave/embedding/transforms.py, dwave/system/composites/embedding.py, tests/test_embedding_composite.py
See https://github.com/dwavesystems/dwave-system/pull/225#issuecomment-532479158
We have not yet deployed so this is not a backwards compatibility break.
=> Default return_embedding parameter to False in EmbeddingComposite

docs/reference/composites.rst, dwave/system/composites/__init__.py, dwave/system/composites/reversecomposite.py, requirements.txt, setup.py, tests/test_reverse_composite.py
Adding two new composites. 
1) `BatchReverseComposite`. that takes in `initial_states `and samples from all of the initial states.
2) `ReverseAdvanceComposite`. takes in `anneal_schedules `and a single `initial_state` (generates a random one if not provided) and does a series of reverse anneal along the given schedule points. The next initial state is chosen such that if `reinitialize_state = True`, it will be the lowest energy most probable state. If `reinitialize_state = False`, the last state returned will be initial state for the next schedule point.
=> Add new composites

docs/reference/composites.rst, dwave/system/composites/embedding.py, dwave/system/warnings.py, setup.py, tests/test_embedding_composite.py
An extremely early prototype implementation of a way we might want to handle warning raising in dwave-system package.
This does not currently support:
* ~~warning types~~
* ~~a warning severity indicator~~
* ~~references to the relevant samples/chains~~
=> Prototype warning generation in EmbeddingComposite

dwave/system/package_info.py, setup.py
For details on dwave contrib mechanism, check dwave-cloud-client#363.
=> Register non-OSS dependancy as a contrib package for `dwave install`

docs/conf.py, docs/intro.rst, dwave/embedding/chain_breaks.py, dwave/embedding/diagnostic.py, dwave/embedding/utils.py, dwave/system/composites/cutoffcomposite.py, dwave/system/composites/embedding.py, dwave/system/composites/tiling.py, dwave/system/composites/virtual_graph.py, dwave/system/samplers/dwave_sampler.py, dwave/system/schedules.py, dwave/system/testing.py, dwave/system/utilities.py, tests/test_leaphybridsolver.py
This PR mocks all `dwave.system` calls to DWaveSampler(), removes doctest skipping, and updates examples for expanded doctest coverage. It needs an update to dwave-ocean-sdk, which I'll make soon, before being merged.
If I have time I'll update MockLeapHybridSolver to work this way too.
```
Doctest summary
===============
174 tests
0 failures in tests
0 failures in setup code
0 failures in cleanup code
build succeeded.
```
=> (Requires SDK update) Mock calls to DWaveSampler to expand doctest coverage

dwave/system/samplers/dwave_sampler.py, tests/test_dwavesampler.py
Naive solution for #273 
Using round() or any rounding method with some tolerance although it requires setting a fixed precision. I used 10 arbitrarily.
Not sure how, but this seems to be managed successfully once the problem is submitted to the machine, maybe the method used there is more appropriate.
=> Naive fix of floating point error in validate anneal. Added test.

docs/reference/samplers.rst, dwave/system/samplers/__init__.py, dwave/system/samplers/clique.py, dwave/system/samplers/dwave_sampler.py, requirements.txt, setup.py, tests/qpu/test_dwavecliquesampler.py, tests/test_dwavecliquesampler.py
Serves as an alternative to #304 and closes #301 . Incorporated the chain strength suggestion in https://github.com/dwavesystems/dwave-system/issues/300#issuecomment-638401351. Makes use of the caching provided to minorminer in https://github.com/dwavesystems/minorminer/pull/133.
Once minorminer 0.2.0 is released, this can be merged (pending review comments of course).
=> Add DWaveCliqueSampler

dwave/embedding/chain_strengths.py, dwave/embedding/transforms.py, dwave/embedding/utils.py, dwave/system/composites/embedding.py, dwave/system/samplers/clique.py, tests/test_embedding_chain_strengths.py, tests/test_embedding_composite.py, tests/test_embedding_transforms.py
Closes #300 .
Addresses the conversation in #326. After discussing with @alexzucca90, I went with an average of 1.33 and 1.5 as our default prefactor (using the formula described by @pau557 [here](https://github.com/dwavesystems/dwave-system/pull/326#issuecomment-685185755)). I didn't implement the topology dependency for reasons described [here](https://github.com/dwavesystems/dwave-system/pull/326#issuecomment-685961599), but perhaps there are other spots that we could do that. For example, @alexzucca90 mentioned that the DWaveCliqueSampler may benefit from using a topology dependent coefficient (as opposed to an average or the current 1.5). 
Also, a lot of the tests in test_embedding_transforms.py are using chain_strength=1. I wasn't entirely sure whether to change them, but can …
=> Improve default chain strength in embed_bqm 

dwave/system/testing.py
To prevent doctest failures such as this one:  https://github.com/dwavesystems/dwave-ocean-sdk/pull/93, in the interest of maximum coverage
```
Document: examples/pp_greedy
File "examples/pp_greedy.rst", line 139, in default
Failed example:
from greedy import SteepestDescentSolver
solver_greedy = SteepestDescentSolver()
sampleset_qpu = sampler.sample_ising(h, J, num_reads=100, answer_mode='raw')
sampleset_pp = solver_greedy.sample_ising(h, J, initial_states=sampleset_qpu)
Exception raised:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/doctest.py", line 1337, in __run
compileflags, 1), test.globs)
File "<doctest default[0]>", line 5, in <module>
sampleset_qpu = sampler.sample_ising(h, J, num_reads=100, answer_mode='raw')
File …
```
=> Add **kwargs to MockDWaveSampler

docs/reference/minimize_energy/dwave.embedding.chain_breaks.MinimizeEnergy.rst, dwave/system/samplers/clique.py, dwave/system/samplers/dwave_sampler.py, dwave/system/samplers/leap_hybrid_sampler.py, dwave/system/utilities.py, requirements.txt, setup.py, tests/qpu/test_dwavecliquesampler.py, tests/qpu/test_dwavesampler.py, tests/qpu/test_embeddingcomposite.py, tests/qpu/test_schedules.py, tests/qpu/test_virtual_graph_composite.py, tests/test_dwavecliquesampler.py, tests/test_dwavesampler.py, tests/test_leaphybridsolver.py
Closes #288.
Closes #335.
(A) and (B) have been implemented, (C) has been dropped for now.
The idea is to have `DWaveSampler`/`DWaveCliqueSampler` and `LeapHybridSampler` auto-select QPU and Hybrid solvers, but allow for user override from a configuration file/environment via `solver` parameter.
=> Specialized dwave samplers

dwave/system/composites/reversecomposite.py, tests/test_reverse_composite.py
Closes #315 
Add default anneal_schedules value of `[[[0, 1], [1, 0.35], [9, 0.35], [10, 1]]] ` to ReverseAdvanceComposite (as suggested by @alexzucca90 )
=> Add default value to ReverseAdvanceComposite's anneal_schedules parameter

docs/reference/composites.rst, docs/reference/samplers.rst
dwave-system part of fix for https://github.com/dwavesystems/dwave-system/issues/380 together with https://github.com/dwavesystems/dimod/pull/775. 
Also makes content lists of samplers/composites look nicer.
=> Add references to additional composites & samplers

dwave/system/samplers/leap_hybrid_sampler.py
The current misalignment messes up the formatting for the function: https://docs.ocean.dwavesys.com/en/stable/docs_system/reference/generated/dwave.system.samplers.LeapHybridDQMSampler.sample_dqm.html#dwave-system-samplers-leaphybriddqmsampler-sample-dqm (for comparison see https://docs.ocean.dwavesys.com/en/stable/docs_system/reference/generated/dwave.system.samplers.DWaveSampler.sample.html#dwave.system.samplers.DWaveSampler.sample)
=> Fix formatting for sample_dqm() docstring

docs/conf.py, docs/requirements.txt, dwave/system/samplers/leap_hybrid_sampler.py
`app.add_stylesheet()` and `app.add_javascript()` were renamed in version 1.8 and obsoleted in version 4
=> Update cookie methods in conf.py

.appveyor.yml, .circleci/config.yml, setup.py, tests/qpu/test_dwavecliquesampler.py, tests/qpu/test_dwavesampler.py, tests/qpu/test_embeddingcomposite.py, tests/qpu/test_leaphybriddqmsampler.py, tests/qpu/test_leaphybridsampler.py, tests/qpu/test_schedules.py, tests/qpu/test_virtual_graph_composite.py
=> CI Refactor

.circleci/config.yml, setup.py
`dwave-preprocessing` was promoted to a full dependency in `dimod==0.10.5` and the `preprocessing` extra install argument was removed. 
This will fix a `pkg_resources.UnknownExtra` error that comes up when another package requires `dwave-system` but `dwave-preprocessing` is not installed (despite `dwave-preprocessing` not being a requirement).
=> Remove use of dimod's preprocessing extra install arg

dwave/system/samplers/clique.py, tests/test_dwavecliquesampler.py
- Add local _ScaleComposite for use with the DWaveCliqueSampler.
- Extends the ScaleComposite class to local _ScaleComposite by checking for per_qubit_coupling_range violation and rescales accordingly.
- Fixes https://github.com/dwavesystems/dwave-system/issues/404
=> Update clique.py: Add local Composite

docs/reference/samplers.rst, dwave/system/__init__.py, dwave/system/samplers/dwave_sampler.py, dwave/system/samplers/leap_hybrid_sampler.py, requirements.txt, tests/test_leaphybridsolver.py
Constrain client type to hybrid, but propagate user-specified solver definition (from config file/env/kwargs).
This is a hybrid analogue of #317 (where we applied the same fix to QPU samplers).
Closes #363.
Partial user-supplied solver definition (patch) is not yet possible, as that requires https://github.com/dwavesystems/dwave-cloud-client/issues/426.
**User-supplied solver mapping will not be updated to fix accepted problems types (bqm/dqm) or version preference.**
So, while this PR fixes the unexpected behavior or user not being able to override the solver in config file/env, it creates a new (less unexpected) gotcha -- whenever user sets `solver` (on any level above `defaults`), that solver filter is used verbatim. For example, users wanting to filter-out bulk solvers will have to …
=> Allow config solver override in hybrid samplers

tests/qpu/test_dwavesampler.py, tests/qpu/test_embeddingcomposite.py, tests/qpu/test_schedules.py, tests/qpu/test_virtual_graph_composite.py
Fix failing `tests.qpu.test_dwavesampler.TestMissingQubits` tests in [build 195](https://app.circleci.com/pipelines/github/dwavesystems/dwave-system/195/workflows/69b25e8d-a78b-4c75-889f-c1a32a2f5136).
=> Make QPU tests insensitive to QPU topology availability

dwave/system/samplers/dwave_sampler.py
**Description of the Change:**
Updated the error message in `sample_ising()` method to suggest using `EmbeddingComposite` when the hardware graph is incompatible with the solver.
**Related Issue:**
Closes #407
=> Suggest using `EmbeddingComposite` when the hardware graph is incompatible

dwave/system/samplers/leap_hybrid_sampler.py, dwave/system/utilities.py, tests/qpu/test_leaphybrid_common.py, tests/test_utilities.py
Add support for feature flags via `DWAVE_FEATURE_FLAGS` env var.
Re-introduce the #363 bug in spirit (hybrid solvers ignore solver def from config file/end), enabled by setting `hss_solver_config_override` feature flag.
This is to support LeapIDE upgrade.
=> Add feature flag `hss_solver_config_override`

dwave/system/composites/tiling.py, dwave/system/testing.py, tests/test_mock_sampler.py, tests/test_tiling_composite.py
The TilingComposite has been modified to allow tiling of Chimera structured problems over Pegasus as well as Chimera solvers.
This is an important use case for certain users, who wish to compare Chimera-structured (or chimera embeddable) problems between the DW2000Q and Advantage generation processors, at high sample density.
Some minor fixes were also introduced for Chimera case, catching some pathological behaviours.
The DWaveMockSampler has been modified to support Pegasus as well as Chimera structured solver emulation.
These changes allow straightforward generalization for the case of Zephyr topologies.
These changes do not resolve all known outstanding issues with TilingComposite e.g. https://github.com/dwavesystems/dwave-system/issues/295 . This supports tiling of Chimera problems …
=> TilingComposite support for Advantage processor

dwave/system/testing.py
qubits and couplers properties are present in DWaveSampler but absent in the MockDWaveSampler.
These properties have been added to MockDWaveSampler
=> Added coupler and qubits parameters to MockDWaveSampler

README.rst
Closes https://github.com/dwavesystems/dwave-system/issues/440 when combined with a change in URL in the repo settings (already done).
=> Remove docs badge

dwave/system/samplers/leap_hybrid_sampler.py
Eliminate deprecation warning that occurs inside `LeapHybridBQMSampler._sample_large`
=> Replace deprecated `bqm.iter_variables`

dwave/system/exceptions.py, dwave/system/samplers/clique.py, dwave/system/samplers/dwave_sampler.py, tests/requirements.txt, tests/test_dwavecliquesampler.py, tests/test_dwavesampler.py
Change in `DWaveSampler`/`DWaveCliqueSampler` behavior: when `failover=True` is specified on construction, solver failover is **only signalled**, and the actual failover is left as an exercise for the developer. :laughing:
The "dirty" bit we solve here is SAPI/solver exception unification:
- if we think sampling call is worth retrying on the same solver, we'll raise `RetryCondition` on sampleset resolve; and
- if we think sampling should be retried on a different solver, we'll raise `FailoverCondition` on sampleset resolve.
Note that `RetryCondition` is a specialization of `FailoverCondition`, so catching `FailoverCondition` and doing `sampler.trigger_failover()` should handle all failover cases.
=> Fix QPU failover - signal solver failover condition (on resolve)

docs/conf.py, dwave/system/testing.py, requirements.txt, setup.py, tests/test_embedding_composite.py, tests/test_mock_sampler.py
By default, problems of size 16 and smaller will be sampled with greedy sampler and then an `ExactSolver`-determined ground state will be injected.
Implements a suggestion from https://github.com/dwavesystems/dwave-system/issues/474#issuecomment-1291026958.
Close #474.
=> Exact-solve for ground state in `MockDWaveSampler` on small problems

dwave/system/samplers/dwave_sampler.py, tests/test_dwavesampler.py
Fix #479.
The amount of `dwave.cloud.Client.get_solver` code/functionality replication turns out to be less then expected. Still not ideal, but probably the best solution without/until cloud-client config refactor.
=> Respect low-level solver order on failover

.appveyor.yml, .circleci/config.yml, dwave/system/samplers/clique.py, dwave/system/samplers/leap_hybrid_sampler.py, dwave/system/testing.py, requirements.txt, setup.py, tests/qpu/test_leaphybridcqmsampler.py, tests/requirements.txt, tests/test_mock_sampler.py
This commit does a few things:
- Bumps the minimum dimod version to a modern version
- Use dwave-samplers rather than dwave-greedy
- Make the versions in requirements.txt match the oldest supported for each package
- Test with the minimum version and latest in CI
- Drop NetworkX from tests/requirements.txt in favour of letting dwave-networkx set the version. This makes our CI a bit simpler at the expense of a bit of explicitness.
=> Simplify dependencies system

dwave/system/samplers/leap_hybrid_sampler.py, tests/test_leaphybridcqmsampler.py
This is a hack for sure, but it doesn't require any changes server-side so can serve for now until we implement https://github.com/dwavesystems/dimod/issues/1303.
See https://github.com/dwavesystems/dwave-system/issues/482
=> Fix LeapHybridCQMSampler time_limit calculation

docs/requirements.txt, tests/test_embedding_chain_breaks.py
Changes the name of the class `TestChainBreakResolutionAPI` to `ChainBreakResolutionAPI`, which is only used for inheritance and is _not_ a collection of tests itself, so that Pytest doesn't pick it up as a test while also keeping unittest happy.
=> Change name of non-test class

dwave/embedding/__init__.py
We document [dwave.embedding.zephyr.find_clique_embedding](https://docs.ocean.dwavesys.com/en/stable/docs_system/reference/generated/dwave.embedding.zephyr.find_clique_embedding.html) but it's not there now:
```
>>> import dwave.embedding
>>> dwave.embedding.zephyr.find_clique_embedding(2, 3)
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 dwave.embedding.zephyr.find_clique_embedding(2, 3)
AttributeError: module 'dwave.embedding' has no attribute 'zephyr'
```
=> Add zephyr to embedding namespace

requirements.txt, setup.py, tests/qpu/test_leaphybriddqmsampler.py
Use a more modern version of dimod to get the benefit of https://github.com/dwavesystems/dimod/pull/1332 and thereby fix the current CI errors in the integration tests on the main branch.
~We could also bump the minimum version in setup.py, but because dimod.CaseLabelDQM is only rarely used, I think it makes sense to be more permissive.~ Ended up requiring `dimod >= 0.12.7`
=> Use dimod 0.12.7 in requirements.txt

.circleci/config.yml, dwave/system/samplers/dwave_sampler.py, requirements.txt, setup.py
In this PR we:
- increase the cloud-client upper bound to 0.12.0
- test with 0.11.0.dev0
- fix docs build for edge case of running tests with a pre-release version of cloud-client that's not yet supported by dwave-system
=> Support cloud-client 0.11.x

dwave/system/samplers/clique.py, tests/qpu/test_dwavecliquesampler.py
Previously the tests would fail if there were other warnings raised.
=> Fix DWaveCliqueSampler integration tests

dwave/system/testing.py, requirements.txt
In cloud-client 0.11.3 we changed the meaning (and type) of a private variable, `Future._sampleset`, as part of garbage collection optimizations in https://github.com/dwavesystems/dwave-cloud-client/pull/602.
=> Adapt `MockLeapHybridSolver` to work with cloud-client 0.11.3+

docs/reference/utilities.rst, dwave/system/temperatures.py, tests/test_temperatures.py
Both flux_biases and h apply time dependent longitudinal fields (fields conjugate to sigma^z in the Hamiltonian description, see documentation).
At given point in the anneal s=t/t_a, h and flux_biases can apply equal longitudinal fields subject to rescaling. If a freeze-out phenomena is assumed at a given s, as relevant to quantum Boltzmann or Boltzmann sampling,  flux_biases can be replaced by h or vice-versa.
'h' is typically unitless, whereas flux has units of Phi0, the conversion is a function of published QPU properties B(s) and M_AFM. This pull request adds code for this conversion.
=> Conversion from flux_biases (units of Phi0) to h (unitless) and vice-versa

dwave/system/testing.py
I'm getting a local test failure on [this line](https://github.com/dwavesystems/dwave-system/blob/eb96379807af275d397378fbef9a703c7d7c696a/tests/qpu/test_dwavesampler.py#L186), I want to see if it's just local or fails in CI too, it wasn't failing before
=> Update ``MockDWaveSampler`` for fast anneal

.circleci/config.yml, requirements.txt
Support for `macos.x86.medium.gen2` is soon to be dropped.
See: https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
=> Use default resource class for macos builds on CircleCi

dwave/system/samplers/leap_hybrid_sampler.py
* Fixes typo in attribute causing link to not work properly. 
* Also removes a few unnecessary whitespaces in docstring.
=> Fix typo in docstring

docs/reference/composites.rst, docs/reference/samplers.rst, docs/reference/warnings.rst, dwave/embedding/transforms.py, dwave/system/composites/cutoffcomposite.py, dwave/system/composites/embedding.py, dwave/system/composites/reversecomposite.py, dwave/system/composites/tiling.py, dwave/system/composites/virtual_graph.py, dwave/system/samplers/clique.py, dwave/system/samplers/dwave_sampler.py, dwave/system/temperatures.py
Part of [sdk](https://github.com/dwavesystems/dwave-ocean-sdk/pull/300), [dimod](https://github.com/dwavesystems/dimod/pull/1372), [dwave-cloud-client](https://github.com/dwavesystems/dwave-cloud-client/pull/633), and [dwave-hybrid](https://github.com/dwavesystems/dwave-hybrid/pull/294) PRs to reduce build warnings
=> Remove ambiguous xrefs to reduce build warnings

dwave/system/composites/virtual_graph.py, tests/test_virtual_graph_composite.py
Closes https://github.com/dwavesystems/dwave-system/issues/531 and https://github.com/dwavesystems/dwave-system/issues/54
=> Deprecate `VirtualGraphComposite`

.circleci/config.yml, dwave/embedding/transforms.py, dwave/system/composites/cutoffcomposite.py, dwave/system/composites/embedding.py, dwave/system/composites/tiling.py, dwave/system/samplers/dwave_sampler.py, requirements.txt, setup.py
=> Add Python 3.13 support and drop Python 3.8 support

requirements.txt, setup.py, tests/qpu/test_leaphybrid_common.py
Make sure sampleset returned always has a working `wait_id()` method.
The fix was actually implemented in https://github.com/dwavesystems/dimod/pull/1393 (released in dimod 0.12.18), and supported with https://github.com/dwavesystems/dwave-cloud-client/pull/674 in cloud-client.
On the dwave-system level, it's enough to require the latest dimod.
Fix #540.
=> Fix inconsistent sampleset interface across hybrid samplers

docs/reference/composites.rst, dwave/system/composites/__init__.py, dwave/system/composites/linear_ancilla.py, releasenotes/notes/add-linear-ancilla-composite-3281ed6733b0f0c7.yaml, tests/test_linear_ancilla_composite.py
In scenarios where the h biases are not available or sufficient in range, one can use auxiliary qubits polarized with a large flux bias and coupled to the data qubit. This method:
-  Requires that each qubit is coupled to a non-programmed qubit
-  But, ancilla qubits can be shared between data qubits
-  The magnitude of the bias is limited by the magnitude of the coupler, but in the case of asymetric coupling range, one can use the strongest coupling available and control the bias sign with the flux bias sign
This PR adds a LinearAncillaComposite that implements this technique.
For the reviewers, please take into account future extensions of this method:
- One can use multiple ancilla qubits to extend the h-range and avoid shrinking energy scales of the problem. This is relevant for QUBO …
=> add LinearAncillaComposite

dwave/system/package_info.py
- Add option to specify sampler used in `MockDWaveSampler` (new default is now `SteepestDescentSampler`). See https://github.com/dwavesystems/dwave-system/pull/537.
- Add support for Python 3.13. See https://github.com/dwavesystems/dwave-system/pull/541.
- Add `LinearAncillaComposite`. See https://github.com/dwavesystems/dwave-system/pull/530.
- Fix inconsistent sampleset interface across hybrid samplers - we make sure every `SampleSet` returned now has a working `wait_id()` method. See https://github.com/dwavesystems/dwave-system/pull/544.
- Drop support for Python 3.8. See https://github.com/dwavesystems/dwave-system/pull/541.
- Soft-remove `VirtualGraphComposite` and its dependencies. Namely, `VirtualGraphComposite` is now just an identity wrapper around `FixedEmbeddingComposite`, …
=> Release 1.28.0

docs/reference/samplers.rst, dwave/system/samplers/clique.py, dwave/system/samplers/dwave_sampler.py, dwave/system/samplers/leap_hybrid_sampler.py, dwave/system/testing.py, tests/qpu/test_dwavecliquesampler.py, tests/qpu/test_dwavesampler.py, tests/qpu/test_leaphybrid_common.py, tests/qpu/test_leaphybridcqmsampler.py, tests/qpu/test_leaphybriddqmsampler.py, tests/qpu/test_leaphybridsampler.py, tests/test_dwavecliquesampler.py, tests/test_dwavesampler.py, tests/test_leaphybridcqmsampler.py, tests/test_leaphybriddqmsolver.py, tests/test_leaphybridnlsampler.py, tests/test_leaphybridsolver.py
Close #77.
Note: ~tests will fail because we need to release `dwave-cloud-client==0.13.3` first.~ We skip tests that require `UseAfterCloseError` from cloud client 0.13.3.
Follow-up: add support for context manager protocol to all samplers.
=> Add `close()` to all QPU and hybrid samplers

dwave/system/samplers/clique.py, dwave/system/samplers/dwave_sampler.py, dwave/system/samplers/leap_hybrid_sampler.py, dwave/system/testing.py, tests/qpu/test_dwavesampler.py, tests/qpu/test_leaphybrid_common.py, tests/test_dwavecliquesampler.py, tests/test_dwavesampler.py, tests/test_leaphybridcqmsampler.py, tests/test_leaphybriddqmsolver.py, tests/test_leaphybridnlsampler.py, tests/test_leaphybridsolver.py
Now all of QPU (`DWaveSampler`, `DWaveCliqueSampler`), and hybrid (`LeapHybrid*Sampler`) samplers support `.close()` and runtime context use.
Close #91.
Composites will be addressed in a follow-up as per #555.
=> Add support for context manager protocol to all samplers

setup.py
Life the maximum version of `dwave-optimization` to `0.7`
=> Support dwave-optimization 0.6.x and 0.7.x

dwave/system/samplers/__init__.py, dwave/system/samplers/leap_hybrid_sampler.py, tests/test_leaphybridnlsampler.py
Close #528.
Opted for the second option from #528, renaming `timing` to `info` and adding general problem info there, together with timing info and warnings.
The `info` field returned in `LeapHybridNLSampler.SampleResult` named tuple is a `dict`, now consistent with `SampleSet.info`, e.g.:
```python
{
"timing": {...},
"warnings": [...],
"problem_id": "...",
"problem_label": "...",
"problem_data_id": "..."
}
```
This change is technically breaking backwards-compatibility, but given that:
- the result type from [`LeapHybridNLSampler.sample()`](https://docs.dwavequantum.com/en/latest/ocean/api_ref_system/generated/dwave.system.samplers.LeapHybridNLSampler.sample.html#dwave.system.samplers.LeapHybridNLSampler.sample) hasn't been documented in full (name of the `timing` field is not …
=> Add problem info to the NL sampler result

.circleci/config.yml, tests/qpu/test_leaphybrid_common.py
Actually implemented in https://github.com/dwavesystems/dwave-cloud-client/pull/690, hence it requires `dwave-cloud-client>=0.13.5`, but we still support ~0.12.0 if this feature is not required.
Close #398.
Note: `problem_data_id` retrieval for the NL solver is implemented in https://github.com/dwavesystems/dwave-system/pull/565.
=> Verify `problem_data_id` returned in sampleset.info with latest client

docs/utilities.rst, dwave/system/utilities.py, tests/test_utilities.py
For DOC-759, will need to be referenced from [Varying the Global Anneal Schedule](https://docs.dwavequantum.com/en/latest/quantum_research/annealing.html#varying-the-global-anneal-schedule) page once in the SDK.
=> Generate energy scales for a custom annealing schedule 

docs/embedding.rst, dwave/system/composites/cutoffcomposite.py, dwave/system/composites/embedding.py, dwave/system/composites/linear_ancilla.py, dwave/system/composites/reversecomposite.py, dwave/system/composites/tiling.py
Currently build issues multiple warnings on the `dimod.Scoped.close` method references and mostly links to cloud-client's close method.
```
CutOffComposite:26: WARNING: more than one target found for cross-reference 'close': dwave.system.samplers.DWaveCliqueSampler.close, dwave.system.samplers.DWaveSampler.close, dwave.system.samplers.LeapHybridCQMSampler.close, dwave.system.samplers.LeapHybridDQMSampler.close, dwave.system.samplers.LeapHybridNLSampler.close, dwave.system.samplers.LeapHybridSampler.close
```
Also, [chain_breaks.MinimizeEnergy](https://docs.dwavequantum.com/en/latest/ocean/api_ref_system/embedding.html#callable-objects) always adding its own directory for the RST stub has long been an annoyance.
=> Fix docbuild warnings on scoped close

dwave/system/package_info.py
- Add `ParallelEmbeddingComposite`, a generalization of the `TilingComposite` that can handle bigger and non-Chimera source graphs on any structured graph supported by `DWaveSampler` (including Zephyr). See [\#569](https://github.com/dwavesystems/dwave-system/pull/569).
- `TilingComposite` is deprecated in favor of `ParallelEmbeddingComposite` and it will be removed in dwave-system 2.0. See [\#577](https://github.com/dwavesystems/dwave-system/pull/577).
- Switch from pkgutil to native namespace package. See [\#571](https://github.com/dwavesystems/dwave-system/pull/571).
=> Release 1.32.0

dwave/embedding/chain_strength.py, dwave/embedding/transforms.py, dwave/system/composites/embedding.py, releasenotes/notes/speed-up-embedding-composites-for-subgraphs-f246b8d1336cb898.yaml, tests/test_embedding_composite.py
Embedding step is ~100x faster and unembedding is ~20x faster (for subgraphs).
(On my laptop, for a Z12 graph, that's 1.7s vs 17ms for embedding and 170ms vs 9ms for unembedding.)
Close #579.
=> Speed-up embedding composites for subgraph embeddings

dwave/embedding/chain_breaks.py
CircleCI is showing just this failure but I might need to fix another that shows up locally (or it might be a difference in Python versions)
This is to deal with the doctest failure in [this PR](https://github.com/dwavesystems/dwave-system/pull/585)
=> Fix broken doctest on ``broken_chains()``

tests/qpu/test_dwavecliquesampler.py
Sometimes the test resolved in (slightly) out-of-range total qubit coupling values. See https://github.com/dwavesystems/dwave-system/issues/591
This is intended to be resolved server-side, after which this commit should be reverted.
=> Remove failing DWaveCliqueSampler test

.circleci/config.yml, dwave/system/package_info.py
-   Begin using reno for changelog.
We began using [Reno](https://docs.openstack.org/reno/) as a changelog tool after the release of 1.32.0. Content added before that release is not included. See [releases](https://github.com/dwavesystems/dwave-system/releases) for previous release notes.
-   Add support for the new solver identity concept available in `dwave-cloud-client>=0.14.0`.
-   Speed-up embedding/unembedding in all embedding composites for the special case of one-to-one embeddings, i.e. subgraphs.
See [\#579](https://github.com/dwavesystems/dwave-system/issues/579).
-   chain\_strength and initial\_state are now supported as sampling options in ParallelEmbeddingComposite. ParallelEmbeddingComposite is updated with an ew sample\_multiple helper function to allow different bqms, …
=> Release 1.33.0
